<?php
       
/*
 * Implementation of hook_menu()
 */
function axelerant_tech_module_menu(){
    $items = array();
    $items['page_json/%/%node'] = array(
        'title' => t('Axelerant Page Json ouput'),
        'page callback' => '_axelerant_tech_module_json_output',
        'page arguments' => array(2),
        'access callback' => '_axelerant_tech_module_json_validate',
		'access arguments' => array(1, 2),
        'type' => MENU_CALLBACK,
    );
    return $items;
}


/*
 * custom validate function
 * to handle the check the arguments to get
 * JSON output of page node type.
 *
*/
function _axelerant_tech_module_json_validate($apicode, $node){
	
	$siteapikey = variable_get('siteapikey', NULL);
	
	//check the apicode matches to siteapikey and the node requested is of "Page" content type.
	if($siteapikey == $apicode && $node->type == 'site_page'){
		return TRUE;
	} else {
		return FALSE;
	}
}


/*
 * custom page callback
 * to handle the request for
 * JSON output of page node type.
 *
*/
function _axelerant_tech_module_json_output($node){
    //return json output of node <page content type>
	drupal_json_output($node);
    exit;
}	   
	   
	   
	   
/*
 * Implementation of hook_form_alter()
 */
function axelerant_tech_module_form_alter(&$form, &$form_state, $form_id){
  //alter system_site_information_settings form to add site api code field.
  
   if($form_id == "system_site_information_settings"){
		
		$siteapikey = variable_get('siteapikey', NULL);
		
		$form['axelerant'] = array(
			'#type' => 'fieldset',
			'#title' => t('Axelerant')
		);
		$form['axelerant']['apicode'] = array(
			'#type' => 'textfield',
			'#title' => t('Site API Key'),
			'#description' => t('Please save the api key required to view the page node type in JSON format.'),
			'#default_value' => (($siteapikey != NULL) ? $siteapikey : t('No API Key yet')),		
		);
		
		$form['actions']['submit']['#value'] = t('Update Configuration');
		
		$form['#submit'][] = '_save_site_api_key_form_submit';
   
   }
}

/*
 * custom submit handler
 * to save api key submitted in
 * site information form.
 *
*/
function _save_site_api_key_form_submit($form, $form_state){
	
	if(!empty($form_state['values']['apicode']) && $form_state['values']['apicode'] != 'No API Key yet'){
	
		variable_set('siteapikey', $form_state['values']['apicode']);
		drupal_set_message(t('Site Api Key <em> @siteapikey </em> has been saved.', array('@siteapikey' => $form_state['values']['apicode'])));
	
	}
	
}


/** Additional Answers: **/
/*
Total Time to Complete the task: 2 hrs.
References: Drupal.org, drupal.stackexchange.com, previous knowledge.
*/